name: Rebrand Aeronics GCS

on:
  workflow_dispatch:

jobs:
  rebrand:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk zipalign imagemagick
          curl -L https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -o apktool.jar
          echo 'java -jar $PWD/apktool.jar "$@"' > apktool
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      - name: Download Base APK
        run: |
          mkdir -p work
          cd work
          curl -L https://github.com/souravghosh92/aeronics-gcs-rebrand/releases/download/Base.apk/base.apk -o base.apk

      - name: Decode APK
        run: |
          cd work
          apktool d -f base.apk -o decoded

      - name: Update manifest (App name)
        run: |
          sed -i 's/android:label="[^"]*"/android:label="Aeronics GCS"/' work/decoded/AndroidManifest.xml

      - name: Replace launcher icon
        run: |
          cd work/decoded
          mkdir -p res/mipmap-anydpi-v26
          cp ../../branding/aeronics_icon_512.png res/mipmap-anydpi-v26/ic_launcher.png
          cp ../../branding/aeronics_icon_512.png res/mipmap-anydpi-v26/ic_launcher_round.png

      - name: Apply overrides
        run: |
          cp -r branding/overrides/* work/decoded/

      - name: Normalize in-app asset sizes
        run: |
          set -e
          cd work/decoded
          A="assets/qml/images"
          fit () {
            in="$1"; w="$2"; h="$3"
            if [ -f "$in" ]; then
              echo "Resizing $in to ${w}x${h}"
              convert "$in" -resize "${w}x${h}"^ \
                -gravity center -background none -extent "${w}x${h}" "$in"
            fi
          }
          # Wide logos for toolbar/about
          fit "$A/qgc_logo_full.png"        300 80
          fit "$A/qground_toolbar_logo.png" 300 80
          fit "$A/title_logo.png"           300 80
          fit "$A/about_logo.png"           360 100
          fit "$A/appbar_logo.png"          360 100
          # Splash logos
          fit "$A/splash_logo.png"         1024 1024
          fit "$A/qgc_splash.png"          1024 1024

      - name: Build APK
        run: |
          cd work/decoded
          apktool b -f -o ../unsigned.apk

      - name: Sign APK
        run: |
          cd work
          mkdir -p keystore
          keytool -genkey -v -keystore keystore/aeronics.jks -keyalg RSA -keysize 2048 -validity 10000 -alias aeronics -storepass password -keypass password -dname "CN=Aeronics"
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore/aeronics.jks -storepass password -keypass password unsigned.apk aeronics
          zipalign -v 4 unsigned.apk Aeronics-GCS.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS
          path: work/Aeronics-GCS.apk
