name: Rebrand QGroundControl to Aeronics GCS
on:
  workflow_dispatch:

jobs:
  rebrand:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Get tools
        run: |
          curl -L -o apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar
          curl -L -o uber-apk-signer.jar https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar

      - name: Download base APK
        run: |
          curl -L -o base.apk https://github.com/souravghosh92/aeronics-gcs-rebrand/releases/download/1.0/QGroundControl.2.apk

      - name: Decode APK
        run: |
          rm -rf work
          java -jar apktool.jar d base.apk -o work -f

      - name: Prepare branding assets
        run: |
          set -e
          mkdir -p branding
          cp -f icon.png branding/icon.png
          cp -f LogoLight.png branding/LogoLight.png || cp -f icon.png branding/LogoLight.png
          cp -f LogoDark.png branding/LogoDark.png || cp -f icon.png branding/LogoDark.png
          cp -f branding/LogoLight.png branding/aeronics_logo.png

      - name: Rename app label
        run: |
          sed -i 's/android:label="[^"]*"/android:label="Aeronics GCS"/' work/AndroidManifest.xml || true
          if ls work/res/values*/strings.xml >/dev/null 2>&1; then
            sed -i 's#<string name="app_name">[^<]*</string>#<string name="app_name">Aeronics GCS</string>#g' work/res/values*/strings.xml || true
          fi

      - name: Replace launcher icons
        run: |
          for d in mipmap-mdpi mipmap-hdpi mipmap-xhdpi mipmap-xxhdpi mipmap-xxxhdpi; do
            cp -f branding/icon.png "work/res/$d/ic_launcher.png" 2>/dev/null || true
            cp -f branding/icon.png "work/res/$d/ic_launcher_round.png" 2>/dev/null || true
          done
          for d in drawable-anydpi-v26 drawable-v26 mipmap-anydpi-v26; do
            cp -f branding/icon.png "work/res/$d/ic_launcher_foreground.png" 2>/dev/null || true
            cp -f branding/icon.png "work/res/$d/ic_launcher_background.png" 2>/dev/null || true
          done

      - name: Replace all drawable icon.png
        run: |
          for d in drawable-ldpi drawable-mdpi drawable-hdpi drawable-xhdpi drawable-xxhdpi drawable-xxxhdpi; do
            cp -f branding/icon.png "work/res/$d/icon.png" 2>/dev/null || true
          done

      - name: Overwrite other QGC logos
        run: |
          for n in qgcLogo.png qgclogo.png QGCLogo.png qgcAppIcon.png productIcon.png toolbarLogo.png appIcon.png AppIcon.png logo.png Logo.png; do
            find work -type f -iname "$n" -exec cp -f branding/aeronics_logo.png {} \; 2>/dev/null || true
          done
          find work -type f -iregex '.*/\(logo\|qgc\)[^/]*\.\(png\|svg\)$' -exec cp -f branding/aeronics_logo.png {} \; 2>/dev/null || true
          find work -type f -iregex '.*/splash[^/]*\.png$' -exec cp -f branding/icon.png {} \; 2>/dev/null || true
          find work -type f -iregex '.*/splash[^/]*\.9\.png$' -exec cp -f branding/icon.png {} \; 2>/dev/null || true

      - name: Replace visible text in QML/JS
        run: |
          for ext in qml js json; do
            grep -RIl --include="*.${ext}" "QGroundControl" work 2>/dev/null | xargs -r sed -i 's/QGroundControl/Aeronics GCS/g'
          done
          grep -RIl --include="*.qml" "QGroundControl Version" work 2>/dev/null | xargs -r sed -i 's/QGroundControl Version/Aeronics GCS Version/g'

      - name: Rebuild unsigned APK
        run: java -jar apktool.jar b work -o unsigned.apk

      - name: Sign & align
        run: |
          mkdir -p output
          java -jar uber-apk-signer.jar -a unsigned.apk -o output

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS-APK
          path: output/*.apk
