name: Rebrand QGroundControl to Aeronics GCS

on:
  workflow_dispatch:

jobs:
  rebrand:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick wget unzip
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      - name: Check required assets exist
        run: |
          if [ ! -f branding/base.apk ]; then
            echo "Missing branding/base.apk"
            exit 1
          fi
          if [ ! -f custom/res/images/aeronics_icon.png ]; then
            echo "Missing custom/res/images/aeronics_icon.png"
            exit 1
          fi

      - name: Decode base APK
        run: |
          java -jar /usr/local/bin/apktool.jar d branding/base.apk -o decoded --force

      - name: Replace launcher + icons
        run: |
          ICON="custom/res/images/aeronics_icon.png"
          cp "$ICON" decoded/res/drawable-nodpi/aeronics_icon.png
          mkdir -p decoded/res/mipmap-anydpi-v26
          cat > decoded/res/mipmap-anydpi-v26/ic_launcher.xml <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@android:color/white"/>
  <foreground>
    <bitmap android:src="@drawable/aeronics_icon" android:gravity="center"/>
  </foreground>
</adaptive-icon>
XML
          cp decoded/res/mipmap-anydpi-v26/ic_launcher.xml decoded/res/mipmap-anydpi-v26/ic_launcher_round.xml

      - name: Rename app
        run: |
          sed -i 's/QGroundControl/Aeronics GCS/g' decoded/res/values/strings.xml || true

      - name: Rebuild APK
        run: |
          java -jar /usr/local/bin/apktool.jar b decoded -o Aeronics-GCS-unsigned.apk

      - name: Sign APK
        run: |
          jarsigner -keystore ~/.android/debug.keystore -storepass android -keypass android \
            Aeronics-GCS-unsigned.apk androiddebugkey
          zipalign -v 4 Aeronics-GCS-unsigned.apk Aeronics-GCS.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Aeronics-GCS-APK
          path: Aeronics-GCS.apk
