name: Rebrand QGroundControl to Aeronics GCS

on:
  workflow_dispatch:

jobs:
  rebrand:
    runs-on: ubuntu-latest

    env:
      RELEASE_TAG: base-apk
      BASE_ASSET: base.apk
      APP_NAME: "Aeronics GCS"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure branding assets exist
        run: |
          set -e
          test -f custom/res/images/aeronics_icon.png  || { echo "Missing aeronics_icon.png"; exit 1; }
          test -f custom/res/images/aeronics_logo.png  || { echo "Missing aeronics_logo.png"; exit 1; }

      - name: Download base.apk from Release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download "$RELEASE_TAG" -p "$BASE_ASSET" -O base.apk
          test -f base.apk || { echo "base.apk not found"; exit 1; }

      - name: Set up Java + Tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y imagemagick openjdk-17-jdk curl
          curl -L -o apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar
          curl -L -o apktool https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          chmod +x apktool
          sudo mv apktool /usr/local/bin/
          mv apktool.jar /usr/local/bin/

      - name: Decode base APK
        run: |
          apktool d -f -o decoded base.apk

      - name: Apply Aeronics launcher icon
        run: |
          ICON="custom/res/images/aeronics_icon.png"
          mkdir -p decoded/res/mipmap-anydpi-v26 decoded/res/drawable-nodpi
          cp "$ICON" decoded/res/drawable-nodpi/aeronics_icon.png

          cat > decoded/res/mipmap-anydpi-v26/ic_launcher.xml <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@android:color/white"/>
  <foreground>
    <bitmap android:src="@drawable/aeronics_icon" android:gravity="center"/>
  </foreground>
</adaptive-icon>
EOF

          cp decoded/res/mipmap-anydpi-v26/ic_launcher.xml decoded/res/mipmap-anydpi-v26/ic_launcher_round.xml

          sed -i 's/android:icon="[^"]*"/android:icon="@mipmap\/ic_launcher"/' decoded/AndroidManifest.xml || true
          sed -i 's/android:roundIcon="[^"]*"/android:roundIcon="@mipmap\/ic_launcher_round"/' decoded/AndroidManifest.xml || true

      - name: Replace Q logos inside menus
        run: |
          SRC_LOGO="custom/res/images/aeronics_logo.png"
          find decoded -type f \( -iname "*qgc*.png" -o -iname "*qground*.png" -o -iname "logo*.png" -o -iname "toolbar*.png" -o -iname "brand*.png" \) | while read -r f; do
            SIZE=$(identify -format "%wx%h" "$f" 2>/dev/null || echo "")
            if [ -n "$SIZE" ]; then
              convert "$SRC_LOGO" -resize "${SIZE}!" "png32:$f"
            else
              cp "$SRC_LOGO" "$f"
            fi
          done

      - name: Replace splash screen if available
        run: |
          if [ -f custom/res/images/splash.png ]; then
            SRC_SPLASH="custom/res/images/splash.png"
            find decoded -type f -iname "splash*.png" | while read -r f; do
              SIZE=$(identify -format "%wx%h" "$f" 2>/dev/null || echo "")
              if [ -n "$SIZE" ]; then
                convert "$SRC_SPLASH" -resize "${SIZE}!" "png32:$f"
              else
                cp "$SRC_SPLASH" "$f"
              fi
            done
          fi

      - name: Replace app text QGroundControl → Aeronics GCS
        run: |
          grep -ril --exclude-dir=.git 'QGroundControl' decoded | xargs -r sed -i 's/QGroundControl/Aeronics GCS/g'
          if [ -f decoded/res/values/strings.xml ]; then
            sed -i 's#<string name="app_name">.*</string>#<string name="app_name">Aeronics GCS</string>#' decoded/res/values/strings.xml || true
          fi

      - name: Rename footer/version labels
        run: |
          grep -ril --exclude-dir=.git 'QGroundControl Version' decoded | xargs -r sed -i 's/QGroundControl Version/Aeronics GCS Version/g'
          grep -ril --exclude-dir=.git 'QGroundControl v' decoded       | xargs -r sed -i 's/QGroundControl v/Aeronics GCS v/g'
          grep -ril --exclude-dir=.git 'About QGroundControl' decoded  | xargs -r sed -i 's/About QGroundControl/About Aeronics GCS/g'

      - name: Rebuild APK
        run: |
          apktool b decoded -o unsigned.apk

      - name: Sign APK
        run: |
          if [ ! -f ~/.android/debug.keystore ]; then
            mkdir -p ~/.android
            keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -keypass android -alias androiddebugkey -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 10000
          fi
          jarsigner -keystore ~/.android/debug.keystore -storepass android -keypass android unsigned.apk androiddebugkey
          mv unsigned.apk Aeronics-GCS.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS-APK
          path: Aeronics-GCS.apk
