name: Rebrand QGC/Mission Planner APK to Aeronics GCS

on:
  workflow_dispatch:
    inputs:
      APK_URL:
        description: "Direct download URL of base APK"
        required: true
        default: "https://github.com/souravghosh92/aeronics-gcs-rebrand/releases/download/Base.apk/base.apk"
      APP_NAME:
        description: "Visible in-app name"
        required: true
        default: "Aeronics GCS"
      ICON_PATH:
        description: "Path to 512x512 PNG inside repo"
        required: true
        default: "branding/aeronics_icon_512.png"
      PACKAGE_ID:
        description: "(Optional) New package id, e.g. in.aeronics.gcs (keeps original if blank)"
        required: false
        default: ""

jobs:
  rebrand:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre-headless wget unzip rsync imagemagick
          # apktool
          sudo curl -L -o /usr/local/bin/apktool https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          sudo chmod +x /usr/local/bin/apktool
          sudo curl -L -o /usr/local/lib/apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar

      - name: Download base APK
        run: |
          set -e
          mkdir -p work
          cd work
          echo "Downloading: ${{ github.event.inputs.APK_URL }}"
          wget -O base.apk "${{ github.event.inputs.APK_URL }}"
          ls -lh base.apk

      - name: Decode APK
        run: |
          set -e
          cd work
          java -jar /usr/local/lib/apktool.jar d -f -o decoded base.apk
          ls -la decoded | sed -n '1,200p'

      # ---------- BRANDING: Launcher icons ----------
      - name: Generate launcher mipmaps from 512x512
        run: |
          set -e
          ICON="${{ github.event.inputs.ICON_PATH }}"
          test -f "$ICON" || { echo "::error ::Icon not found at $ICON"; exit 1; }

          mkdir -p work/decoded/res/mipmap-mdpi work/decoded/res/mipmap-hdpi work/decoded/res/mipmap-xhdpi work/decoded/res/mipmap-xxhdpi work/decoded/res/mipmap-xxxhdpi

          convert "$ICON" -resize 48x48   work/decoded/res/mipmap-mdpi/ic_launcher.png
          convert "$ICON" -resize 72x72   work/decoded/res/mipmap-hdpi/ic_launcher.png
          convert "$ICON" -resize 96x96   work/decoded/res/mipmap-xhdpi/ic_launcher.png
          convert "$ICON" -resize 144x144 work/decoded/res/mipmap-xxhdpi/ic_launcher.png
          convert "$ICON" -resize 192x192 work/decoded/res/mipmap-xxxhdpi/ic_launcher.png

          # Round variants
          for d in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
            cp work/decoded/res/mipmap-$d/ic_launcher.png work/decoded/res/mipmap-$d/ic_launcher_round.png
          done

          # Ensure manifest icons point to ours
          sed -i 's/android:icon="[^"]*"/android:icon="@mipmap\/ic_launcher"/' work/decoded/AndroidManifest.xml || true
          sed -i 's/android:roundIcon="[^"]*"/android:roundIcon="@mipmap\/ic_launcher_round"/' work/decoded/AndroidManifest.xml || true

      # ---------- BRANDING: In-app images ----------
      # Put your Aeronics logo at: branding/overrides/assets/qml/images/aeronics_logo.png
      - name: Replace in-app Q logos (toolbar/splash/about)
        run: |
          set -e
          SRC_LOGO="$GITHUB_WORKSPACE/branding/overrides/assets/qml/images/aeronics_logo.png"
          IMG_DST="work/decoded/assets/qml/images"
          mkdir -p "$IMG_DST"
          if [ -f "$SRC_LOGO" ]; then
            cp "$SRC_LOGO" "$IMG_DST/aeronics_logo.png"
          else
            echo "::warning ::No Aeronics in-app logo found at $SRC_LOGO (skipping image swap)"; 
          fi

          echo "== Existing logo-ish assets =="
          find work/decoded -type f -iregex '.*\(logo\|qgc.*\|qground.*\).*\.\(png\|svg\)' | sed -n '1,200p' || true

          # Overwrite common QGC/QGroundControl logo filenames if present
          for f in qground_toolbar_logo.png qgc_logo_full.png appbar_logo.png title_logo.png splash_logo.png about_logo.png qgc_splash.png; do
            if [ -f "$IMG_DST/$f" ] && [ -f "$IMG_DST/aeronics_logo.png" ]; then
              echo "Overriding $f -> aeronics_logo.png"
              cp "$IMG_DST/aeronics_logo.png" "$IMG_DST/$f"
            fi
          done

          # Rewrite QML references to point to aeronics_logo.png
          if [ -d work/decoded/assets/qml ]; then
            grep -RIl --null -e 'qground_toolbar_logo.png\|qgc_logo_full.png\|appbar_logo.png\|title_logo.png\|splash_logo.png\|about_logo.png\|qgc_splash.png' work/decoded/assets/qml \
            | xargs -0 -r sed -i 's/qground_toolbar_logo.png/aeronics_logo.png/g; s/qgc_logo_full.png/aeronics_logo.png/g; s/appbar_logo.png/aeronics_logo.png/g; s/title_logo.png/aeronics_logo.png/g; s/splash_logo.png/aeronics_logo.png/g; s/about_logo.png/aeronics_logo.png/g; s/qgc_splash.png/aeronics_logo.png/g'
          fi

          echo "== Remaining Q* logo refs (should be empty) =="
          grep -RIn 'qgc.*logo\|qground.*logo' work/decoded/assets/qml || true

      # Optional: overlay any extra images you drop in the repo
      - name: Overlay extra QML images (optional)
        run: |
          set -e
          SRC_DIR="$GITHUB_WORKSPACE/branding/overrides/assets/qml/images"
          DST_DIR="work/decoded/assets/qml/images"
          mkdir -p "$DST_DIR"
          if [ -d "$SRC_DIR" ]; then
            rsync -av --no-perms --no-owner --no-group "$SRC_DIR/" "$DST_DIR/"
          else
            echo "No additional QML image overrides at $SRC_DIR (skipping)."
          fi
          ls -la "$DST_DIR" | sed -n '1,200p' || true

      # ---------- BRANDING: Names/strings ----------
      - name: Patch in-app name (strings + manifest + assets/QML text)
        run: |
          set -e
          APPNAME="${{ github.event.inputs.APP_NAME }}"

          # Force manifest label to use @string/app_name
          sed -i 's/android:label="[^"]*"/android:label="@string\/app_name"/' work/decoded/AndroidManifest.xml || true

          # Optional: change package id if provided
          if [ -n "${{ github.event.inputs.PACKAGE_ID }}" ]; then
            sed -i 's/package="\([^"]*\)"/package="${{ github.event.inputs.PACKAGE_ID }}"/' work/decoded/AndroidManifest.xml || true
          fi

          # Inject our string resources overlay
          mkdir -p work/decoded/res/values
          cat > work/decoded/res/values/strings_aeronics.xml <<EOF
          <resources>
            <string name="app_name">${APPNAME}</string>
            <string name="brand_name">Aeronics</string>
            <string name="app_full_name">${APPNAME}</string>
          </resources>
          EOF

          # Replace hard-coded brand strings in assets (About/QML text)
          if [ -d work/decoded/assets ]; then
            grep -RIl --null -e 'QGroundControl' work/decoded/assets | xargs -0 -r sed -i "s/QGroundControl/${APPNAME}/g"
            grep -RIl --null -e 'Mission Planner' work/decoded/assets | xargs -0 -r sed -i "s/Mission Planner/${APPNAME}/g"
          fi

          # Normalize any android:title attributes to use app_name
          find work/decoded/res -type f -name '*.xml' -print0 | xargs -0 -r sed -i 's/android:title="[^"]*"/android:title="@string\/app_name"/g'

          echo "✔ In-app name set to: ${APPNAME}"

      # ---------- BUILD + SIGN ----------
      - name: Build APK with apktool
        run: |
          set -e
          cd work/decoded
          java -jar /usr/local/lib/apktool.jar b -f -o ../unsigned.apk
          ls -lh ../unsigned.apk

      - name: Sign & align APK (uber-apk-signer)
        run: |
          set -e
          cd work
          wget -q https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O signer.jar
          java -jar signer.jar --apks unsigned.apk
          echo "Signed APKs found:"
          ls -lh *Signed.apk
          # Prefer releaseSigned; fall back to debugSigned
          APK_FILE=$(ls *-releaseSigned.apk 2>/dev/null || ls *-debugSigned.apk | head -n1)
          cp "$APK_FILE" Aeronics-GCS.apk
          ls -lh Aeronics-GCS.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS
          path: work/Aeronics-GCS.apk
