name: Rebrand QGroundControl to Aeronics GCS (with overrides)

on:
  workflow_dispatch:
    inputs:
      QGC_APK_URL:
        description: "Direct download URL of QGroundControl APK"
        required: true
      APP_NAME:
        description: "Visible app name"
        default: "Aeronics GCS"

jobs:
  rebrand:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ github.event.inputs.APP_NAME }}
      ICON: branding/aeronics_icon_512.png

    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y default-jre zipalign apksigner imagemagick curl
          mkdir -p $HOME/bin
          curl -L -o $HOME/bin/apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar
          printf '#!/usr/bin/env bash\nexec java -jar $HOME/bin/apktool.jar "$@"\n' > $HOME/bin/apktool
          chmod +x $HOME/bin/apktool
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify apktool
        run: apktool --version

      - name: Download APK
        run: |
          set -e
          mkdir -p work && cd work
          curl -L --fail -o qgc.apk "${{ github.event.inputs.QGC_APK_URL }}"
          ls -lh qgc.apk

      - name: Decode APK
        run: |
          set -e
          cd work
          apktool d -f -o decoded qgc.apk

      - name: Set manifest label + ensure native libs extraction
        run: |
          set -e
          cd work/decoded
          # Safer: literal label (no res edits)
          if grep -q 'android:label=' AndroidManifest.xml; then
            sed -i 's#android:label="[^"]*"#android:label="'"${APP_NAME}"'"#' AndroidManifest.xml
          else
            sed -i 's#<application #<application android:label="'"${APP_NAME}"'" #' AndroidManifest.xml
          fi
          # Prevent crash on native libs
          if grep -q 'android:extractNativeLibs=' AndroidManifest.xml; then
            sed -i 's#android:extractNativeLibs="[^"]*"#android:extractNativeLibs="true"#' AndroidManifest.xml
          else
            sed -i 's#<application #<application android:extractNativeLibs="true" #' AndroidManifest.xml
          fi

      - name: Replace launcher icons (overwrite existing only)
        run: |
          set -e
          cd work/decoded
          if [ ! -f "$GITHUB_WORKSPACE/$ICON" ]; then
            echo "::error ::Missing branding/aeronics_icon_512.png (upload 512x512 PNG)"; exit 1
          fi
          mapfile -t files < <(find res -type f -name "ic_launcher*.png" | sort)
          if [ "${#files[@]}" -eq 0 ]; then
            echo "::warning ::No ic_launcher*.png found; launcher icon unchanged."
          fi
          for f in "${files[@]}"; do
            sz=$(identify -format "%wx%h" "$f" 2>/dev/null || echo "192x192")
            echo "Overwriting $f with $sz"
            convert "$GITHUB_WORKSPACE/$ICON" -resize "$sz" "$f"
          done

      - name: List likely QGC logo files (to help you create overrides)
        run: |
          set -e
          cd work/decoded
          echo "=== Possible in-app logo files ==="
          # common patterns for QGC assets
          find res -type f \( -iname "*logo*.png" -o -iname "*qgc*.png" -o -iname "*qground*.png" \) | sort | tee $GITHUB_WORKSPACE/likely_logo_files.txt
      - name: Upload logo filename list
        uses: actions/upload-artifact@v4
        with:
          name: likely-logo-files
          path: likely_logo_files.txt
          if-no-files-found: ignore

      - name: Apply precise overrides from branding/overrides (same names/paths)
        run: |
          set -e
          cd work/decoded
          SRC="$GITHUB_WORKSPACE/branding/overrides"
          if [ -d "$SRC" ]; then
            echo "Applying overrides from $SRC"
            while IFS= read -r -d '' f; do
              rel="${f#"$SRC/"}"
              if [ -f "$rel" ]; then
                cp -f "$f" "$rel"
                echo "Override applied: $rel"
              else
                # If destination folder doesn’t exist (rare), skip to avoid build errors
                echo "::warning ::Destination $rel not found in APK; skipped"
              fi
            done < <(find "$SRC" -type f -print0)
          else
            echo "No branding/overrides directory; skipping precise overrides."
          fi

      - name: Build (verbose)
        run: |
          set -e
          cd work
          set +e
          apktool b -v decoded -o Aeronics-GCS-unsigned.apk 2>&1 | tee build.log
          status=${PIPESTATUS[0]}
          set -e
          if [ $status -ne 0 ]; then
            echo "=== Build failed (tail) ==="; tail -n 200 build.log || true
            exit $status
          fi

      - name: Align, sign, verify
        run: |
          set -e
          cd work
          zipalign -f 4 Aeronics-GCS-unsigned.apk Aeronics-GCS-aligned.apk
          keytool -genkey -v -keystore debug.keystore -storepass android \
            -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Aeronics,O=Aeronics"
          apksigner sign --ks debug.keystore --ks-pass pass:android \
            --key-pass pass:android --out Aeronics-GCS.apk Aeronics-GCS-aligned.apk
          apksigner verify Aeronics-GCS.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS-APK
          path: work/Aeronics-GCS.apk
