name: Rebrand QGroundControl to Aeronics GCS

on:
  workflow_dispatch:

jobs:
  rebrand:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip zip openjdk-17-jdk

      - name: Download apktool & uber-apk-signer
        run: |
          curl -L -o apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar
          curl -L -o apktool https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          chmod +x apktool
          curl -L -o uber-apk-signer.jar https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar

      - name: Download base QGroundControl APK
        run: |
          curl -L -o base.apk https://github.com/souravghosh92/aeronics-gcs-rebrand/releases/download/1.0/QGroundControl.2.apk

      - name: Decode APK
        run: |
          java -jar apktool.jar d base.apk -o decoded-apk --force

      - name: Apply Aeronics Branding
        run: |
          # Replace icons & logos
          cp custom/res/images/aeronics_icon.png decoded-apk/res/mipmap-xxhdpi-v4/ic_launcher.png
          cp custom/res/images/aeronics_icon.png decoded-apk/res/mipmap-xxxhdpi-v4/ic_launcher.png
          cp custom/res/images/aeronics_logo.png decoded-apk/res/drawable/logo.png
          cp custom/res/images/splash.png decoded-apk/res/drawable/splash.png

          # Add qrc and plugin
          mkdir -p decoded-apk/custom
          cp qgc_custom.qrc decoded-apk/custom/qgc_custom.qrc
          cp CustomPlugin.cc decoded-apk/custom/CustomPlugin.cc

          # Replace text branding
          find decoded-apk -type f -name "*.xml" -exec sed -i 's/QGroundControl/Aeronics GCS/g' {} +
          find decoded-apk -type f -name "*.smali" -exec sed -i 's/QGroundControl/Aeronics GCS/g' {} +

      - name: Rebuild APK
        run: |
          java -jar apktool.jar b decoded-apk -o Aeronics-GCS-unsigned.apk

      - name: Sign APK
        run: |
          java -jar uber-apk-signer.jar --apks Aeronics-GCS-unsigned.apk
          mv Aeronics-GCS-unsigned-aligned-debugSigned.apk Aeronics-GCS.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS-APK
          path: Aeronics-GCS.apk
