name: Rebrand QGroundControl to Aeronics GCS

on:
  workflow_dispatch:

jobs:
  rebrand:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk imagemagick zipalign aapt libimage-exiftool-perl
          curl -L -o apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar
          curl -L -o apktool https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          chmod +x apktool
          curl -L -o uber-apk-signer.jar https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar

      - name: Download Base APK
        run: curl -L "https://github.com/souravghosh92/aeronics-gcs-rebrand/releases/download/1.0/QGroundControl.2.apk" -o base.apk

      - name: Decode APK
        run: java -jar apktool.jar d -f -o decoded-apk base.apk

      - name: Replace branding
        run: |
          # Change app name
          sed -i 's/QGroundControl/Aeronics GCS/g' decoded-apk/AndroidManifest.xml || true
          find decoded-apk/res -type f -name "*.xml" -exec sed -i 's/QGroundControl/Aeronics GCS/g' {} +
          find decoded-apk/res -type f -name "*.xml" -exec sed -i 's/QGC/Aeronics GCS/g' {} +

          # Replace icons
          for d in decoded-apk/res/mipmap-*; do
            cp custom/res/images/aeronics_icon.png "$d/ic_launcher.png" || true
            cp custom/res/images/aeronics_icon.png "$d/ic_launcher_round.png" || true
          done

          # Replace splash/logo if present
          find decoded-apk -type f -iname "*splash*.png" -exec cp custom/res/images/splash.png {} \; || true
          find decoded-apk -type f -iname "*logo*.png" -exec cp custom/res/images/aeronics_logo.png {} \; || true

      - name: Rebuild APK
        run: java -jar apktool.jar b decoded-apk -o unsigned.apk

      - name: Align and Sign
        run: |
          zipalign -p -f 4 unsigned.apk aligned.apk
          java -jar uber-apk-signer.jar --allowResign -a aligned.apk --out signed

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS-APK
          path: signed/*.apk
