name: Rebrand QGroundControl to Aeronics GCS

on:
  workflow_dispatch:

jobs:
  rebrand:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/build-tools/34.0.0:${{ env.PATH }}
      BASE_APK: branding/base.apk
      ICON: custom/res/images/aeronics_icon.png
      APP_NAME: "Aeronics GCS"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip zipalign apksigner imagemagick curl

      - name: Install Android SDK
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          curl -L -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q tools.zip -d latest
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-31" "build-tools;34.0.0" "platform-tools"

      - name: Download apktool
        run: |
          curl -L -o /usr/local/bin/apktool https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          curl -L -o /usr/local/bin/apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar
          chmod +x /usr/local/bin/apktool

      - name: Check required assets
        run: |
          test -f "$BASE_APK" || (echo "Missing $BASE_APK"; exit 1)
          test -f "$ICON" || (echo "Missing icon at $ICON"; exit 1)

      - name: Decode base APK
        run: apktool d -f -o decoded "$BASE_APK"

      - name: Apply branding
        run: |
          sed -i 's/android:label="[^"]*"/android:label="'${APP_NAME}'"/' decoded/AndroidManifest.xml || true
          sed -i 's/android:icon="[^"]*"/android:icon="@mipmap\/ic_launcher"/' decoded/AndroidManifest.xml || true
          mkdir -p decoded/res/drawable-nodpi
          cp "$ICON" decoded/res/drawable-nodpi/aeronics_icon.png

      - name: Rebuild APK
        run: apktool b decoded -o unsigned.apk

      - name: Zipalign
        run: zipalign -v -p 4 unsigned.apk aligned.apk

      - name: Sign APK
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Aer, OU=Dev, O=Aer, L=City, S=State, C=US"
          apksigner sign --ks debug.keystore --ks-pass pass:android --key-pass pass:android --out Aeronics-GCS.apk aligned.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS-APK
          path: Aeronics-GCS.apk
