name: Rebrand Aeronics GCS
on:
  workflow_dispatch:

jobs:
  rebrand:
    runs-on: ubuntu-latest
    env:
      BASE_APK_URL: https://github.com/souravghosh92/aeronics-gcs-rebrand/releases/download/Base.apk/base.apk
      APP_NAME: Aeronics GCS
      ICON_PATH: branding/aeronics_icon_512.png

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools (apktool, ImageMagick, JDK, UberApkSigner)
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y default-jdk imagemagick zipalign curl
          # apktool (jar + wrapper)
          sudo curl -L -o /usr/local/bin/apktool.jar https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar
          echo 'exec java -jar /usr/local/bin/apktool.jar "$@"' | sudo tee /usr/local/bin/apktool >/dev/null
          sudo chmod +x /usr/local/bin/apktool
          # Uber APK Signer
          mkdir -p "$HOME/bin"
          curl -L -o "$HOME/bin/uber-apk-signer.jar" https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar
          apktool --version

      - name: Download Base APK
        run: |
          set -e
          mkdir -p work
          cd work
          curl -L "$BASE_APK_URL" -o base.apk
          ls -lh base.apk

      - name: Decode APK
        run: |
          set -e
          cd work
          apktool d -f base.apk -o decoded
          test -d decoded

      # Optional: keep this to see paths inside APK when needed
      - name: List possible logos
        run: |
          cd work/decoded
          echo "=== Searching for logo/splash/launcher files in APK ==="
          { find res -type f \( -iname "*ic_launcher*" -o -iname "*logo*.*" -o -iname "*qgc*.*" -o -iname "*qground*.*" -o -iname "*splash*.*" \) 2>/dev/null;
            find assets -type f \( -iname "*logo*.*" -o -iname "*qgc*.*" -o -iname "*qground*.*" -o -iname "*splash*.*" \) 2>/dev/null; } \
          | sort | tee "$GITHUB_WORKSPACE/image-map.txt"

      - name: Upload image map
        uses: actions/upload-artifact@v4
        with:
          name: image-map
          path: image-map.txt

      - name: Update manifest (app label + extractNativeLibs)
        run: |
          set -e
          cd work/decoded
          # Change visible app name
          if grep -q 'android:label=' AndroidManifest.xml; then
            sed -i 's#android:label="[^"]*"#android:label="'"$APP_NAME"'"#' AndroidManifest.xml
          else
            sed -i 's#<application #<application android:label="'"$APP_NAME"'" #' AndroidManifest.xml
          fi
          # Ensure native libs extracted
          if grep -q 'android:extractNativeLibs=' AndroidManifest.xml; then
            sed -i 's#android:extractNativeLibs="[^"]*"#android:extractNativeLibs="true"#' AndroidManifest.xml
          else
            sed -i 's#<application #<application android:extractNativeLibs="true" #' AndroidManifest.xml
          fi

      - name: Replace launcher icons (all densities + adaptive)
        run: |
          set -e
          cd work/decoded
          ICON="$GITHUB_WORKSPACE/$ICON_PATH"
          if [ ! -f "$ICON" ]; then
            echo "::error ::Missing $ICON_PATH (512x512 PNG)"; exit 1
          fi

          # Adaptive foreground/background (used by XML)
          mkdir -p res/drawable
          convert "$ICON" -resize 432x432 res/drawable/ic_launcher_foreground.png
          convert -size 108x108 xc:"#FFFFFF" res/drawable/ic_launcher_background.png

          # Patch adaptive xmls if present
          if [ -d res/mipmap-anydpi-v26 ]; then
            for xml in res/mipmap-anydpi-v26/ic_launcher*.xml; do
              [ -f "$xml" ] || continue
              sed -i 's#@mipmap/ic_launcher_foreground#@drawable/ic_launcher_foreground#g' "$xml" || true
              sed -i 's#@mipmap/ic_launcher_background#@drawable/ic_launcher_background#g' "$xml" || true
              sed -i 's#@drawable-anydpi/ic_launcher_foreground#@drawable/ic_launcher_foreground#g' "$xml" || true
              sed -i 's#@drawable-anydpi/ic_launcher_background#@drawable/ic_launcher_background#g' "$xml" || true
              echo "Patched $xml"
            done
          fi

          # Overwrite legacy PNGs in all densities (note the -v4 folders)
          for spec in mdpi:48 hdpi:72 xhdpi:96 xxhdpi:144 xxxhdpi:192; do
            den=${spec%%:*}; size=${spec##*:}
            for folder in "res/mipmap-$den" "res/mipmap-$den-v4"; do
              for name in ic_launcher.png ic_launcher_round.png; do
                dest="$folder/$name"
                if [ -f "$dest" ]; then
                  convert "$ICON" -resize ${size}x${size} "$dest"
                  echo "Replaced $dest"
                fi
              done
            done
          done

      - name: Apply in-app Aeronics logos (exact paths from image-map)
        run: |
          set -e
          # Copy your assets explicitly (use the exact paths found in image-map.txt)
          cp branding/overrides/assets/qml/images/about_logo.png            work/decoded/assets/qml/images/about_logo.png            || true
          cp branding/overrides/assets/qml/images/appbar_logo.png           work/decoded/assets/qml/images/appbar_logo.png           || true
          cp branding/overrides/assets/qml/images/qgc_logo_full.png         work/decoded/assets/qml/images/qgc_logo_full.png         || true
          cp branding/overrides/assets/qml/images/qgc_splash.png            work/decoded/assets/qml/images/qgc_splash.png            || true
          cp branding/overrides/assets/qml/images/qground_toolbar_logo.png  work/decoded/assets/qml/images/qground_toolbar_logo.png  || true
          cp branding/overrides/assets/qml/images/splash_logo.png           work/decoded/assets/qml/images/splash_logo.png           || true
          cp branding/overrides/assets/qml/images/title_logo.png            work/decoded/assets/qml/images/title_logo.png            || true

      - name: Build APK
        run: |
          set -e
          cd work/decoded
          apktool b -f -o ../unsigned.apk
          ls -lh ../unsigned.apk

      - name: Sign & Align (Uber APK Signer)
        run: |
          set -e
          cd work
          java -jar "$HOME/bin/uber-apk-signer.jar" --apks unsigned.apk --out .
          out_apk=$(ls *-aligned-*-signed.apk | head -n 1 || true)
          if [ -z "$out_apk" ]; then
            out_apk=$(ls *-aligned-*.apk | head -n 1 || true)
          fi
          if [ -z "$out_apk" ]; then
            echo "::error ::Signing failed (no output APK)"; exit 1
          fi
          mv "$out_apk" Aeronics-GCS.apk
          ls -lh Aeronics-GCS.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aeronics-GCS.apk
          path: work/Aeronics-GCS.apk
